import kotlinx.datetime.*
import java.io.File

fun main(args: Array<String>) {
    println("Hello World!")

    // Try adding program arguments via Run/Debug configuration.
    // Learn more about running applications: https://www.jetbrains.com/help/idea/running-applications.html.
    println("Program arguments: ${args.joinToString()}")

    val resourcesDirectory = File("src/resources/flag")

    println(resourcesDirectory.isDirectory)
    println(resourcesDirectory.path)

}

data class Country(
    val code: String? = null,
    val name: String? = null,
    val dialCode: String? = null,
    val flag: String? = null,
    val currency: String? = null,
)

private val COUNTRIES = arrayOf(
    Country(
        "AD",
        "Andorra",
        "+376",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ad.svg",
        "EUR"
    ),
    Country(
        "AE",
        "United Arab Emirates",
        "+971",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ae.svg",
        "AED"
    ),
    Country(
        "AF",
        "Afghanistan",
        "+93",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/af.svg",
        "AFN"
    ),
    Country(
        "AG",
        "Antigua and Barbuda",
        "+1-268",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ag.svg",
        "XCD"
    ),
    Country(
        "AI",
        "Anguilla",
        "+1-264",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ai.svg",
        "XCD"
    ),
    Country(
        "AL",
        "Albania",
        "+355",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/al.svg",
        "ALL"
    ),
    Country(
        "AM",
        "Armenia",
        "+374",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/am.svg",
        "AMD"
    ),
    Country(
        "AN",
        "Netherlands Antilles",
        "+599",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/an.svg",
        "ANG"
    ),
    Country(
        "AO",
        "Angola",
        "+244",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ao.svg",
        "AOA"
    ),
    Country(
        "AQ",
        "Antarctica",
        "+672",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/aq.svg",
        "USD"
    ),
    Country(
        "AR",
        "Argentina",
        "+54",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ar.svg",
        "ARS"
    ),
    Country(
        "AS",
        "American Samoa",
        "+1-684",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/as.svg",
        "USD"
    ),
    Country(
        "AT",
        "Austria",
        "+43",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/at.svg",
        "EUR"
    ),
    Country(
        "AU",
        "Australia",
        "+61",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/au.svg",
        "AUD"
    ),
    Country("AW", "Aruba", "+297", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/aw.svg", "AWG"),
    Country(
        "AZ",
        "Azerbaijan",
        "+994",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/az.svg",
        "AZN"
    ),
    Country(
        "BA",
        "Bosnia and Herzegovina",
        "+387",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ba.svg",
        "BAM"
    ),
    Country(
        "BB",
        "Barbados",
        "+1-246",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bb.svg",
        "BBD"
    ),
    Country(
        "BD",
        "Bangladesh",
        "+880",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bd.svg",
        "BDT"
    ),
    Country(
        "BE",
        "Belgium",
        "+32",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/be.svg",
        "EUR"
    ),
    Country(
        "BF",
        "Burkina Faso",
        "+226",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bf.svg",
        "XOF"
    ),
    Country(
        "BG",
        "Bulgaria",
        "+359",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bg.svg",
        "BGN"
    ),
    Country(
        "BH",
        "Bahrain",
        "+973",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bh.svg",
        "BHD"
    ),
    Country(
        "BI",
        "Burundi",
        "+257",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bi.svg",
        "BIF"
    ),
    Country("BJ", "Benin", "+229", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bj.svg", "XOF"),
    Country(
        "BL",
        "Saint Barthelemy",
        "+590",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bl.svg",
        "EUR"
    ),
    Country(
        "BM",
        "Bermuda",
        "+1-441",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bm.svg",
        "BMD"
    ),
    Country(
        "BN",
        "Brunei",
        "+673",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bn.svg",
        "BND"
    ),
    Country(
        "BO",
        "Bolivia",
        "+591",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bo.svg",
        "BOB"
    ),
    Country("BR", "Brazil", "+55", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/br.svg", "BRL"),
    Country(
        "BS",
        "Bahamas",
        "+1-242",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bs.svg",
        "BSD"
    ),
    Country(
        "BT",
        "Bhutan",
        "+975",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bt.svg",
        "BTN"
    ),
    Country(
        "BW",
        "Botswana",
        "+267",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bw.svg",
        "BWP"
    ),
    Country(
        "BY",
        "Belarus",
        "+375",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/by.svg",
        "BYR"
    ),
    Country(
        "BZ",
        "Belize",
        "+501",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/bz.svg",
        "BZD"
    ),
    Country("CA", "Canada", "+1", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ca.svg", "CAD"),
    Country(
        "CC",
        "Cocos Islands",
        "+61",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cc.svg",
        "AUD"
    ),
    Country(
        "CD",
        "Democratic Republic of the Congo",
        "+243",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cd.svg",
        "CDF"
    ),
    Country(
        "CF",
        "Central African Republic",
        "+236",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cf.svg",
        "XAF"
    ),
    Country(
        "CG",
        "Republic of the Congo",
        "+242",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cg.svg",
        "XAF"
    ),
    Country(
        "CH",
        "Switzerland",
        "+41",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ch.svg",
        "CHF"
    ),
    Country(
        "CI",
        "Ivory Coast",
        "+225",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ci.svg",
        "XOF"
    ),
    Country(
        "CK",
        "Cook Islands",
        "+682",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ck.svg",
        "NZD"
    ),
    Country("CL", "Chile", "+56", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cl.svg", "CLP"),
    Country(
        "CM",
        "Cameroon",
        "+237",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cm.svg",
        "XAF"
    ),
    Country("CN", "China", "+86", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cn.svg", "CNY"),
    Country(
        "CO",
        "Colombia",
        "+57",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/co.svg",
        "COP"
    ),
    Country(
        "CR",
        "Costa Rica",
        "+506",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cr.svg",
        "CRC"
    ),
    Country("CU", "Cuba", "+53", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cu.svg", "CUP"),
    Country(
        "CV",
        "Cape Verde",
        "+238",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cv.svg",
        "CVE"
    ),
    Country(
        "CW",
        "Curacao",
        "+599",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cw.svg",
        "ANG"
    ),
    Country(
        "CX",
        "Christmas Island",
        "+61",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cx.svg",
        "AUD"
    ),
    Country(
        "CY",
        "Cyprus",
        "+357",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cy.svg",
        "EUR"
    ),
    Country(
        "CZ",
        "Czech Republic",
        "+420",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/cz.svg",
        "CZK"
    ),
    Country(
        "DE",
        "Germany",
        "+49",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/de.svg",
        "EUR"
    ),
    Country(
        "DJ",
        "Djibouti",
        "+253",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/dj.svg",
        "DJF"
    ),
    Country(
        "DK",
        "Denmark",
        "+45",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/dk.svg",
        "DKK"
    ),
    Country(
        "DM",
        "Dominica",
        "+1-767",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/dm.svg",
        "XCD"
    ),
    Country(
        "DO",
        "Dominican Republic",
        "+1-809, +1-829, +1-849",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/do.svg",
        "DOP"
    ),
    Country(
        "DZ",
        "Algeria",
        "+213",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/dz.svg",
        "DZD"
    ),
    Country(
        "EC",
        "Ecuador",
        "+593",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ec.svg",
        "USD"
    ),
    Country(
        "EE",
        "Estonia",
        "+372",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ee.svg",
        "EUR"
    ),
    Country("EG", "Egypt", "+20", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/eg.svg", "EGP"),
    Country(
        "EH",
        "Western Sahara",
        "+212",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/eh.svg",
        "MAD"
    ),
    Country(
        "ER",
        "Eritrea",
        "+291",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/er.svg",
        "ERN"
    ),
    Country("ES", "Spain", "+34", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/es.svg", "EUR"),
    Country(
        "ET",
        "Ethiopia",
        "+251",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/et.svg",
        "ETB"
    ),
    Country(
        "FI",
        "Finland",
        "+358",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/fi.svg",
        "EUR"
    ),
    Country("FJ", "Fiji", "+679", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/fj.svg", "FJD"),
    Country(
        "FK",
        "Falkland Islands",
        "+500",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/fk.svg",
        "FKP"
    ),
    Country(
        "FM",
        "Micronesia",
        "+691",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/fm.svg",
        "USD"
    ),
    Country(
        "FO",
        "Faroe Islands",
        "+298",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/fo.svg",
        "DKK"
    ),
    Country("FR", "France", "+33", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/fr.svg", "EUR"),
    Country("GA", "Gabon", "+241", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ga.svg", "XAF"),
    Country(
        "GB",
        "United Kingdom",
        "+44",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gb.svg",
        "GBP"
    ),
    Country(
        "GD",
        "Grenada",
        "+1-473",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gd.svg",
        "XCD"
    ),
    Country(
        "GE",
        "Georgia",
        "+995",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ge.svg",
        "GEL"
    ),
    Country(
        "GG",
        "Guernsey",
        "+44-1481",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gg.svg",
        "GGP"
    ),
    Country("GH", "Ghana", "+233", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gh.svg", "GHS"),
    Country(
        "GI",
        "Gibraltar",
        "+350",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gi.svg",
        "GIP"
    ),
    Country(
        "GL",
        "Greenland",
        "+299",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gl.svg",
        "DKK"
    ),
    Country(
        "GM",
        "Gambia",
        "+220",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gm.svg",
        "GMD"
    ),
    Country(
        "GN",
        "Guinea",
        "+224",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gn.svg",
        "GNF"
    ),
    Country(
        "GQ",
        "Equatorial Guinea",
        "+240",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gq.svg",
        "XAF"
    ),
    Country("GR", "Greece", "+30", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gr.svg", "EUR"),
    Country(
        "GT",
        "Guatemala",
        "+502",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gt.svg",
        "GTQ"
    ),
    Country(
        "GU",
        "Guam",
        "+1-671",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gu.svg",
        "USD"
    ),
    Country(
        "GW",
        "Guinea-Bissau",
        "+245",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gw.svg",
        "XOF"
    ),
    Country(
        "GY",
        "Guyana",
        "+592",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/gy.svg",
        "GYD"
    ),
    Country(
        "HK",
        "Hong Kong",
        "+852",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/hk.svg",
        "HKD"
    ),
    Country(
        "HN",
        "Honduras",
        "+504",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/hn.svg",
        "HNL"
    ),
    Country(
        "HR",
        "Croatia",
        "+385",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/hr.svg",
        "HRK"
    ),
    Country("HT", "Haiti", "+509", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ht.svg", "HTG"),
    Country(
        "HU",
        "Hungary",
        "+36",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/hu.svg",
        "HUF"
    ),
    Country(
        "ID",
        "Indonesia",
        "+62",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/id.svg",
        "IDR"
    ),
    Country(
        "IE",
        "Ireland",
        "+353",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ie.svg",
        "EUR"
    ),
    Country(
        "IL",
        "Israel",
        "+972",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/il.svg",
        "ILS"
    ),
    Country(
        "IM",
        "Isle of Man",
        "+44-1624",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/im.svg",
        "GBP"
    ),
    Country("IN", "India", "+91", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/in.svg", "INR"),
    Country(
        "IO",
        "British Indian Ocean Territory",
        "+246",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/io.svg",
        "USD"
    ),
    Country("IQ", "Iraq", "+964", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/iq.svg", "IQD"),
    Country("IR", "Iran", "+98", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ir.svg", "IRR"),
    Country(
        "IS",
        "Iceland",
        "+354",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/is.svg",
        "ISK"
    ),
    Country("IT", "Italy", "+39", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/it.svg", "EUR"),
    Country(
        "JE",
        "Jersey",
        "+44-1534",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/je.svg",
        "JEP"
    ),
    Country(
        "JM",
        "Jamaica",
        "+1-876",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/jm.svg",
        "JMD"
    ),
    Country(
        "JO",
        "Jordan",
        "+962",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/jo.svg",
        "JOD"
    ),
    Country("JP", "Japan", "+81", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/jp.svg", "JPY"),
    Country("KE", "Kenya", "+254", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ke.svg", "KES"),
    Country(
        "KG",
        "Kyrgyzstan",
        "+996",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/kg.svg",
        "KGS"
    ),
    Country(
        "KH",
        "Cambodia",
        "+855",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/kh.svg",
        "KHR"
    ),
    Country(
        "KI",
        "Kiribati",
        "+686",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ki.svg",
        "AUD"
    ),
    Country(
        "KM",
        "Comoros",
        "+269",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/km.svg",
        "KMF"
    ),
    Country(
        "KN",
        "Saint Kitts and Nevis",
        "+1-869",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/kn.svg",
        "XCD"
    ),
    Country(
        "KP",
        "North Korea",
        "+850",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/kp.svg",
        "KPW"
    ),
    Country(
        "KR",
        "South Korea",
        "+82",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/kr.svg",
        "KRW"
    ),
    Country(
        "KW",
        "Kuwait",
        "+965",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/kw.svg",
        "KWD"
    ),
    Country(
        "KY",
        "Cayman Islands",
        "+1-345",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ky.svg",
        "KYD"
    ),
    Country(
        "KZ",
        "Kazakhstan",
        "+7",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/kz.svg",
        "KZT"
    ),
    Country("LA", "Laos", "+856", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/la.svg", "LAK"),
    Country(
        "LB",
        "Lebanon",
        "+961",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/lb.svg",
        "LBP"
    ),
    Country(
        "LC",
        "Saint Lucia",
        "+1-758",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/lc.svg",
        "XCD"
    ),
    Country(
        "LI",
        "Liechtenstein",
        "+423",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/li.svg",
        "CHF"
    ),
    Country(
        "LK",
        "Sri Lanka",
        "+94",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/lk.svg",
        "LKR"
    ),
    Country(
        "LR",
        "Liberia",
        "+231",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/lr.svg",
        "LRD"
    ),
    Country(
        "LS",
        "Lesotho",
        "+266",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ls.svg",
        "LSL"
    ),
    Country(
        "LT",
        "Lithuania",
        "+370",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/lt.svg",
        "LTL"
    ),
    Country(
        "LU",
        "Luxembourg",
        "+352",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/lu.svg",
        "EUR"
    ),
    Country(
        "LV",
        "Latvia",
        "+371",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/lv.svg",
        "LVL"
    ),
    Country("LY", "Libya", "+218", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ly.svg", "LYD"),
    Country(
        "MA",
        "Morocco",
        "+212",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ma.svg",
        "MAD"
    ),
    Country(
        "MC",
        "Monaco",
        "+377",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mc.svg",
        "EUR"
    ),
    Country(
        "MD",
        "Moldova",
        "+373",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/md.svg",
        "MDL"
    ),
    Country(
        "ME",
        "Montenegro",
        "+382",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/me.svg",
        "EUR"
    ),
    Country(
        "MF",
        "Saint Martin",
        "+590",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mf.svg",
        "EUR"
    ),
    Country(
        "MG",
        "Madagascar",
        "+261",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mg.svg",
        "MGA"
    ),
    Country(
        "MH",
        "Marshall Islands",
        "+692",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mh.svg",
        "USD"
    ),
    Country(
        "MK", "Macedonia", "+389", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mk.svg",
        "MKD"
    ),
    Country("ML", "Mali", "+223", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ml.svg", "XOF"),
    Country(
        "MM",
        "Myanmar",
        "+95",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mm.svg",
        "MMK"
    ),
    Country(
        "MN",
        "Mongolia",
        "+976",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mn.svg",
        "MNT"
    ),
    Country("MO", "Macao", "+853", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mo.svg", "MOP"),
    Country(
        "MP",
        "Northern Mariana Islands",
        "+1-670",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mp.svg",
        "USD"
    ),
    Country(
        "MR",
        "Mauritania",
        "+222",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mr.svg",
        "MRO"
    ),
    Country(
        "MS",
        "Montserrat",
        "+1-664",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ms.svg",
        "XCD"
    ),
    Country("MT", "Malta", "+356", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mt.svg", "EUR"),
    Country(
        "MU",
        "Mauritius",
        "+230",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mu.svg",
        "MUR"
    ),
    Country(
        "MV",
        "Maldives",
        "+960",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mv.svg",
        "MVR"
    ),
    Country(
        "MW",
        "Malawi",
        "+265",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mw.svg",
        "MWK"
    ),
    Country("MX", "Mexico", "+52", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mx.svg", "MXN"),
    Country(
        "MY",
        "Malaysia",
        "+60",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/my.svg",
        "MYR"
    ),
    Country(
        "MZ",
        "Mozambique",
        "+258",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/mz.svg",
        "MZN"
    ),
    Country(
        "NA",
        "Namibia",
        "+264",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/na.svg",
        "NAD"
    ),
    Country(
        "NC",
        "New Caledonia",
        "+687",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/nc.svg",
        "XPF"
    ),
    Country("NE", "Niger", "+227", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ne.svg", "XOF"),
    Country(
        "NG",
        "Nigeria",
        "+234",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ng.svg",
        "NGN"
    ),
    Country(
        "NI",
        "Nicaragua",
        "+505",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ni.svg",
        "NIO"
    ),
    Country(
        "NL",
        "Netherlands",
        "+31",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/nl.svg",
        "EUR"
    ),
    Country("NO", "Norway", "+47", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/no.svg", "NOK"),
    Country("NP", "Nepal", "+977", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/np.svg", "NPR"),
    Country("NR", "Nauru", "+674", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/nr.svg", "AUD"),
    Country("NU", "Niue", "+683", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/nu.svg", "NZD"),
    Country(
        "NZ",
        "New Zealand",
        "+64",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/nz.svg",
        "NZD"
    ),
    Country("OM", "Oman", "+968", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/om.svg", "OMR"),
    Country(
        "PA",
        "Panama",
        "+507",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pa.svg",
        "PAB"
    ),
    Country("PE", "Peru", "+51", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pe.svg", "PEN"),
    Country(
        "PF",
        "French Polynesia",
        "+689",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pf.svg",
        "XPF"
    ),
    Country(
        "PG",
        "Papua New Guinea",
        "+675",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pg.svg",
        "PGK"
    ),
    Country(
        "PH",
        "Philippines",
        "+63",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ph.svg",
        "PHP"
    ),
    Country(
        "PK",
        "Pakistan",
        "+92",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pk.svg",
        "PKR"
    ),
    Country("PL", "Poland", "+48", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pl.svg", "PLN"),
    Country(
        "PM",
        "Saint Pierre and Miquelon",
        "+508",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pm.svg",
        "EUR"
    ),
    Country(
        "PN",
        "Pitcairn",
        "+64",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pn.svg",
        "NZD"
    ),
    Country(
        "PR",
        "Puerto Rico",
        "+1-787, +1-939",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pr.svg",
        "USD"
    ),
    Country(
        "PS",
        "Palestinian",
        "+970",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ps.svg",
        "ILS"
    ),
    Country(
        "PT",
        "Portugal",
        "+351",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pt.svg",
        "EUR"
    ),
    Country("PW", "Palau", "+680", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/pw.svg", "USD"),
    Country(
        "PY",
        "Paraguay",
        "+595",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/py.svg",
        "PYG"
    ),
    Country("QA", "Qatar", "+974", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/qa.svg", "QAR"),
    Country(
        "RE",
        "Reunion",
        "+262",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/re.svg",
        "EUR"
    ),
    Country(
        "RO",
        "Romania",
        "+40",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ro.svg",
        "RON"
    ),
    Country(
        "RS",
        "Serbia",
        "+381",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/rs.svg",
        "RSD"
    ),
    Country("RU", "Russia", "+7", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ru.svg", "RUB"),
    Country(
        "RW",
        "Rwanda",
        "+250",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/rw.svg",
        "RWF"
    ),
    Country(
        "SA",
        "Saudi Arabia",
        "+966",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sa.svg",
        "SAR"
    ),
    Country(
        "SB",
        "Solomon Islands",
        "+677",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sb.svg",
        "SBD"
    ),
    Country(
        "SC",
        "Seychelles",
        "+248",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sc.svg",
        "SCR"
    ),
    Country("SD", "Sudan", "+249", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sd.svg", "SDG"),
    Country("SE", "Sweden", "+46", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/se.svg", "SEK"),
    Country(
        "SG",
        "Singapore",
        "+65",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sg.svg",
        "SGD"
    ),
    Country(
        "SH", "Saint Helena", "+290", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sh.svg",
        "SHP"
    ),
    Country(
        "SI",
        "Slovenia",
        "+386",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/si.svg",
        "EUR"
    ),
    Country(
        "SJ",
        "Svalbard and Jan Mayen",
        "+47",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sj.svg",
        "NOK"
    ),
    Country(
        "SK",
        "Slovakia",
        "+421",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sk.svg",
        "EUR"
    ),
    Country(
        "SL",
        "Sierra Leone",
        "+232",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sl.svg",
        "SLL"
    ),
    Country(
        "SM",
        "San Marino",
        "+378",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sm.svg",
        "EUR"
    ),
    Country(
        "SN",
        "Senegal",
        "+221",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sn.svg",
        "XOF"
    ),
    Country(
        "SO",
        "Somalia",
        "+252",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/so.svg",
        "SOS"
    ),
    Country(
        "SR",
        "Suriname",
        "+597",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sr.svg",
        "SRD"
    ),
    Country(
        "SS",
        "South Sudan",
        "+211",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ss.svg",
        "SSP"
    ),
    Country(
        "ST",
        "Sao Tome and Principe",
        "+239",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/st.svg",
        "STD"
    ),
    Country(
        "SV",
        "El Salvador",
        "+503",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sv.svg",
        "SVC"
    ),
    Country(
        "SX",
        "Sint Maarten",
        "+1-721",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sx.svg",
        "ANG"
    ),
    Country("SY", "Syria", "+963", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sy.svg", "SYP"),
    Country(
        "SZ",
        "Swaziland",
        "+268",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/sz.svg",
        "SZL"
    ),
    Country(
        "TC",
        "Turks and Caicos Islands",
        "+1-649",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tc.svg",
        "USD"
    ),
    Country("TD", "Chad", "+235", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/td.svg", "XAF"),
    Country("TG", "Togo", "+228", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tg.svg", "XOF"),
    Country(
        "TH",
        "Thailand",
        "+66",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/th.svg",
        "THB"
    ),
    Country(
        "TJ",
        "Tajikistan",
        "+992",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tj.svg",
        "TJS"
    ),
    Country(
        "TK",
        "Tokelau",
        "+690",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tk.svg",
        "NZD"
    ),
    Country(
        "TL",
        "East Timor",
        "+670",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tl.svg",
        "USD"
    ),
    Country(
        "TM",
        "Turkmenistan",
        "+993",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tm.svg",
        "TMT"
    ),
    Country(
        "TN",
        "Tunisia",
        "+216",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tn.svg",
        "TND"
    ),
    Country("TO", "Tonga", "+676", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/to.svg", "TOP"),
    Country("TR", "Turkey", "+90", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tr.svg", "TRY"),
    Country(
        "TT",
        "Trinidad and Tobago",
        "+1-868",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tt.svg",
        "TTD"
    ),
    Country(
        "TV",
        "Tuvalu",
        "+688",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tv.svg",
        "AUD"
    ),
    Country(
        "TW",
        "Taiwan",
        "+886",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tw.svg",
        "TWD"
    ),
    Country(
        "TZ",
        "Tanzania",
        "+255",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/tz.svg",
        "TZS"
    ),
    Country(
        "UA",
        "Ukraine",
        "+380",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ua.svg",
        "UAH"
    ),
    Country(
        "UG",
        "Uganda",
        "+256",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ug.svg",
        "UGX"
    ),
    Country(
        "US",
        "United States",
        "+1",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/us.svg",
        "USD"
    ),
    Country(
        "UY",
        "Uruguay",
        "+598",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/uy.svg",
        "UYU"
    ),
    Country(
        "UZ",
        "Uzbekistan",
        "+998",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/uz.svg",
        "UZS"
    ),
    Country(
        "VA",
        "Vatican",
        "+379",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/va.svg",
        "EUR"
    ),
    Country(
        "VC",
        "Saint Vincent and the Grenadines",
        "+1-784",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/vc.svg",
        "XCD"
    ),
    Country(
        "VE",
        "Venezuela",
        "+58",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ve.svg",
        "VEF"
    ),
    Country(
        "VG",
        "British Virgin Islands",
        "+1-284",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/vg.svg",
        "USD"
    ),
    Country(
        "VI",
        "U.S. Virgin Islands",
        "+1-340",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/vi.svg",
        "USD"
    ),
    Country(
        "VN",
        "Vietnam",
        "+84",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/vn.svg",
        "VND"
    ),
    Country(
        "VU",
        "Vanuatu",
        "+678",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/vu.svg",
        "VUV"
    ),
    Country(
        "WF",
        "Wallis and Futuna",
        "+681",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/wf.svg",
        "XPF"
    ),
    Country("WS", "Samoa", "+685", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ws.svg", "WST"),
    Country(
        "XK",
        "Kosovo",
        "+383",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/xk.svg",
        "EUR"
    ),
    Country("YE", "Yemen", "+967", "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/ye.svg", "YER"),
    Country(
        "YT",
        "Mayotte",
        "+262",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/yt.svg",
        "EUR"
    ),
    Country(
        "ZA",
        "South Africa",
        "+27",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/za.svg",
        "ZAR"
    ),
    Country(
        "ZM",
        "Zambia",
        "+260",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/zm.svg",
        "ZMW"
    ),
    Country(
        "ZW",
        "Zimbabwe",
        "+263",
        "https://github.com/sunnat629/CountriesDetails/blob/master/flags/svg/zw.svg",
        "USD"
    )
)